apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    app: my-app
spec:
  containers:
    - name: nginx-container1
      image: nginx:latest
      ports:
        - containerPort: 80
    - name: redis-container2
      image: redis:latest
      ports:
        - containerPort: 6379 

